title: root💀Sayonara:~#
#description: Try Harder!!!
show_downloads: false
show_repo: false
theme: jekyll-theme-hacker

gems:
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

socialIcons:
    - name: github
      url: "https://github.com/ismail-arame"
    - name: discord
      url: "Sayonara9328"
